# Generated by Django 5.1.7 on 2025-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
